version: "3.8"

services:
  workspace:
    container_name: "devcontainer"
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.clion
    ports:
      - "2222:22"
    networks:
      - workspace_network
    cap_add:
      - SYS_PTRACE

networks:
  workspace_network:
    driver: "bridge"
