version: "3.8"

services:
  workspace:
    container_name: "devcontainer"
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.clion
    ports:
      - "2222:22"
    networks:
      - workspace_network
    # for profiling so that kernel.kptr_resrict=0 and kernel.perf_event_paranoid=1 can be set properly
    privileged: true
    cap_add:
      - SYS_PTRACE

networks:
  workspace_network:
    driver: "bridge"
